"use strict";

module.exports = {
    "extends": [
        "stylelint-config-standard",
        "stylelint-config-recommended-scss"
    ],
    "plugins": [
        "stylelint-scss",
        "stylelint-order"
    ],
    "rules": {
        "at-rule-name-case": "lower",
        "at-rule-name-space-after": "always",
        "at-rule-no-vendor-prefix": true,
        "at-rule-semicolon-newline-after": "always",

        "order/properties-order": [
            "position",
            "top",
            "right",
            "bottom",
            "left",
            "z-index",
            "box-sizing",
            "display",
            "flex",
            "flex-align",
            "flex-basis",
            "flex-direction",
            "flex-wrap",
            "flex-flow",
            "flex-shrink",
            "flex-grow",
            "flex-order",
            "flex-pack",
            "align-content",
            "align-items",
            "align-self",
            "justify-content",
            "order",
            "float",
            "width",
            "min-width",
            "max-width",
            "height",
            "min-height",
            "max-height",
            "padding",
            "padding-top",
            "padding-right",
            "padding-bottom",
            "padding-left",
            "margin",
            "margin-top",
            "margin-right",
            "margin-bottom",
            "margin-left",
            "overflow",
            "overflow-x",
            "overflow-y",
            "-webkit-overflow-scrolling",
            "-ms-overflow-x",
            "-ms-overflow-y",
            "-ms-overflow-style",
            "columns",
            "column-count",
            "column-fill",
            "column-gap",
            "column-rule",
            "column-rule-width",
            "column-rule-style",
            "column-rule-color",
            "column-span",
            "column-width",
            "orphans",
            "widows",
            "clip",
            "clear",
            "font",
            "font-family",
            "font-size",
            "font-style",
            "font-weight",
            "font-variant",
            "font-size-adjust",
            "font-stretch",
            "font-effect",
            "font-emphasize",
            "font-emphasize-position",
            "font-emphasize-style",
            "font-smooth",
            "src",
            "hyphens",
            "line-height",
            "color",
            "text-align",
            "text-align-last",
            "text-emphasis",
            "text-emphasis-color",
            "text-emphasis-style",
            "text-emphasis-position",
            "text-decoration",
            "text-indent",
            "text-justify",
            "text-outline",
            "-ms-text-overflow",
            "text-overflow",
            "text-overflow-ellipsis",
            "text-overflow-mode",
            "text-shadow",
            "text-transform",
            "text-wrap",
            "-webkit-text-size-adjust",
            "-ms-text-size-adjust",
            "letter-spacing",
            "-ms-word-break",
            "word-break",
            "word-spacing",
            "-ms-word-wrap",
            "word-wrap",
            "overflow-wrap",
            "tab-size",
            "white-space",
            "vertical-align",
            "direction",
            "unicode-bidi",
            "list-style",
            "list-style-position",
            "list-style-type",
            "list-style-image",
            "pointer-events",
            "-ms-touch-action",
            "touch-action",
            "cursor",
            "visibility",
            "zoom",
            "table-layout",
            "empty-cells",
            "caption-side",
            "border-spacing",
            "border-collapse",
            "content",
            "quotes",
            "counter-reset",
            "counter-increment",
            "resize",
            "user-select",
            "nav-index",
            "nav-up",
            "nav-right",
            "nav-down",
            "nav-left",
            "background",
            "background-color",
            "background-image",
            "filter",
            "background-repeat",
            "background-attachment",
            "background-position",
            "background-position-x",
            "background-position-y",
            "background-clip",
            "background-origin",
            "background-size",
            "border",
            "border-color",
            "border-style",
            "border-width",
            "border-top",
            "border-top-color",
            "border-top-style",
            "border-top-width",
            "border-right",
            "border-right-color",
            "border-right-style",
            "border-right-width",
            "border-bottom",
            "border-bottom-color",
            "border-bottom-style",
            "border-bottom-width",
            "border-left",
            "border-left-color",
            "border-left-style",
            "border-left-width",
            "border-radius",
            "border-top-left-radius",
            "border-top-right-radius",
            "border-bottom-right-radius",
            "border-bottom-left-radius",
            "border-image",
            "border-image-source",
            "border-image-slice",
            "border-image-width",
            "border-image-outset",
            "border-image-repeat",
            "outline",
            "outline-width",
            "outline-style",
            "outline-color",
            "outline-offset",
            "box-shadow",
            "opacity",
            "-ms-interpolation-mode",
            "page-break-after",
            "page-break-before",
            "page-break-inside",
            "transition",
            "transition-delay",
            "transition-timing-function",
            "transition-duration",
            "transition-property",
            "transform",
            "transform-origin",
            "perspective",
            "appearance",
            "animation",
            "animation-name",
            "animation-duration",
            "animation-play-state",
            "animation-timing-function",
            "animation-delay",
            "animation-iteration-count",
            "animation-direction",
            "animation-fill-mode",
            "fill",
            "stroke"
        ],

        "block-no-empty": true,
        "block-no-single-line": true,
        "block-opening-brace-newline-after": "always",
        "block-opening-brace-newline-before": "never-single-line",
        "block-opening-brace-space-before": "always",

        "color-hex-case": "lower",
        "color-hex-length": "long",
        "color-named": "never",
        "color-no-invalid-hex": true,

        "comment-empty-line-before": "always",
        "comment-whitespace-inside": "always",

        "declaration-bang-space-after": "never",
        "declaration-bang-space-before": "always",
        "declaration-block-no-duplicate-properties": true,
        "declaration-block-no-ignored-properties": true,
        "declaration-block-no-shorthand-property-overrides": true,
        "declaration-block-semicolon-space-after": "always-single-line",
        "declaration-block-single-line-max-declarations": 1,
        "declaration-block-trailing-semicolon": "always",

        "declaration-colon-space-after": "always",
        "declaration-colon-space-before": "never",

        "font-family-name-quotes": "always-unless-keyword",
        "font-weight-notation": "numeric",

        "function-calc-no-unspaced-operator": true,
        "function-comma-newline-after": "never-multi-line",
        "function-comma-newline-before": "never-multi-line",
        "function-comma-space-after": "always",
        "function-comma-space-before": "never",

        "function-linear-gradient-no-nonstandard-direction": true,

        "function-max-empty-lines": 0,

        "function-parentheses-space-inside": "never",
        "function-url-quotes": "always",
        "function-whitespace-after": "always",

        "indentation": 4,
        "length-zero-no-unit": true,
        "max-empty-lines": 2,
        "max-nesting-depth": 4,

        "media-feature-colon-space-after": "always",
        "media-feature-colon-space-before": "never",
        "media-feature-name-no-vendor-prefix": true,
        "media-feature-no-missing-punctuation": true,
        "media-feature-range-operator-space-after": "always",
        "media-feature-range-operator-space-before": "always",
        "media-feature-parentheses-space-inside": "never",

        "no-duplicate-selectors": true,
        "no-eol-whitespace": true,
        "no-extra-semicolons": true,
        "no-indistinguishable-colors": [true, {
            ignore: ['#f5f5f5'],
        }],
        "no-missing-end-of-source-newline": true,

        "number-leading-zero": "never",
        "number-max-precision": 2,
        "number-no-trailing-zeros": true,

        "property-case": "lower",
        "property-no-vendor-prefix": true,

        "root-no-standard-properties": true,
        "rule-nested-empty-line-before": ["always", {
            except: "first-nested",
        }],
        "rule-non-nested-empty-line-before": "always",

        "selector-attribute-brackets-space-inside": "never",

        "selector-attribute-operator-space-after": "never",
        "selector-attribute-operator-space-before":  "never",

        "selector-combinator-space-after": "always",
        "selector-combinator-space-before": "always",

        "selector-list-comma-space-after": "always-single-line",
        "selector-list-comma-space-before": "never",

        "selector-max-empty-lines": 0,
        "selector-max-compound-selectors": 3,

        "selector-no-id": true,
        "selector-no-vendor-prefix": true,
        "selector-pseudo-class-case": "lower",
        "selector-pseudo-class-no-unknown": true,
        "selector-pseudo-class-parentheses-space-inside": "never",
        "selector-pseudo-element-case": "lower",
        "selector-pseudo-element-colon-notation": "double",
        "selector-pseudo-element-no-unknown": true,
        "selector-root-no-composition": true,
        "selector-type-case": "lower",
        "selector-type-no-unknown": true,
        "shorthand-property-no-redundant-values": true,

        "string-no-newline": true,
        "string-quotes": "double",

        "time-no-imperceptible": true,

        "unit-case": "lower",
        "unit-no-unknown": true,

        "value-keyword-case": "lower",
        "value-list-comma-space-after": "always",
        "value-list-comma-space-before": "never",

        "value-no-vendor-prefix": true,
    }
}
